#!/usr/bin/env python3
"""
wav_to_cpp.py — convert drop-in WAV files into compile-time C++ sample blobs.

Reads 16-bit mono 44.1 kHz WAVs from assets/samples/ and emits two files
under generated/:

  - samples.hpp : SampleId enum + SampleDescriptor + table declaration
  - samples.cpp : per-sample int16_t arrays in flash + table definition

A fixed canonical sample set is always emitted. If a WAV is missing or has
the wrong format, that slot gets a single-sample silent stub so the firmware
still builds. Files are rewritten only when their content actually changes
so the PlatformIO incremental build is preserved.
"""
from __future__ import annotations

import os
import struct
import sys
import wave
from pathlib import Path
from typing import List, Optional, Tuple

# Canonical sample set — order is the on-wire SampleId.
# (enum name, [accepted filename aliases]) — first existing file wins.
CANONICAL: List[Tuple[str, List[str]]] = [
    ("KICK",         ["kick.wav"]),
    ("SNARE",        ["snare.wav"]),
    ("HIHAT_OPEN",   ["hihat_open.wav", "open_highhat.wav", "open_hihat.wav"]),
    ("HIHAT_CLOSED", ["hihat_closed.wav", "highhat.wav", "hihat.wav", "closed_hihat.wav"]),
    ("RIDE",         ["ride.wav"]),
    ("COWBELL",      ["cowbell.wav"]),
    ("STICKS",       ["sticks.wav"]),
    ("CRASH",        ["crash.wav", "crush.wav"]),
    ("TOM",          ["tom.wav"]),
]

EXPECTED_SAMPLE_RATE = 44100
EXPECTED_CHANNELS    = 1
EXPECTED_SAMPLE_W    = 2   # bytes per sample (16-bit)

# Cap individual samples so a stray multi-megabyte file can't blow flash.
MAX_SAMPLES_PER_FILE = 2_000_000   # ~4 MB at 16-bit → bigger than typical 4 MB flash anyway


def read_wav(path: Path) -> Optional[List[int]]:
    """Return signed-int16 PCM samples, or None if the file is malformed."""
    try:
        with wave.open(str(path), "rb") as wf:
            sr   = wf.getframerate()
            ch   = wf.getnchannels()
            sw   = wf.getsampwidth()
            n    = wf.getnframes()
            data = wf.readframes(n)
    except (wave.Error, OSError) as e:
        print(f"  ! {path.name}: cannot read ({e})", file=sys.stderr)
        return None

    if sr != EXPECTED_SAMPLE_RATE:
        print(f"  ! {path.name}: sample rate {sr} != {EXPECTED_SAMPLE_RATE}", file=sys.stderr)
        return None
    if ch != EXPECTED_CHANNELS:
        print(f"  ! {path.name}: channels {ch} != {EXPECTED_CHANNELS}", file=sys.stderr)
        return None
    if sw != EXPECTED_SAMPLE_W:
        print(f"  ! {path.name}: sample width {sw*8} bit != 16 bit", file=sys.stderr)
        return None
    if n == 0:
        print(f"  ! {path.name}: empty", file=sys.stderr)
        return None
    if n > MAX_SAMPLES_PER_FILE:
        print(f"  ! {path.name}: {n} samples exceeds cap {MAX_SAMPLES_PER_FILE}", file=sys.stderr)
        return None

    return list(struct.unpack(f"<{n}h", data))


def render_array(name: str, samples: List[int]) -> str:
    """Pretty-print one sample array, 16 values per line."""
    lines = [f"static constexpr int16_t {name}[] = {{"]
    width = 16
    for i in range(0, len(samples), width):
        chunk = ", ".join(f"{v:6d}" for v in samples[i:i + width])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    """Write content to path only if it differs from what's already there."""
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def emit_header(out: Path) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/wav_to_cpp.py — do not edit by hand.",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace dummer { namespace audio {",
        "",
        "enum SampleId : uint8_t {",
    ]
    for i, (enum_name, _) in enumerate(CANONICAL):
        lines.append(f"    SAMPLE_{enum_name} = {i},")
    lines.append(f"    SAMPLE_COUNT = {len(CANONICAL)},")
    lines.append("};")
    lines.append("")
    lines.append("struct SampleDescriptor {")
    lines.append("    const int16_t* data;")
    lines.append("    uint32_t       length;")
    lines.append("};")
    lines.append("")
    lines.append("extern const SampleDescriptor kSampleTable[SAMPLE_COUNT];")
    lines.append("")
    lines.append("}} // namespace dummer::audio")
    lines.append("")
    write_if_changed(out, "\n".join(lines))


def emit_source(out: Path, samples_dir: Path) -> None:
    body: List[str] = [
        "// AUTO-GENERATED by scripts/wav_to_cpp.py — do not edit by hand.",
        '#include "samples.hpp"',
        "",
        "namespace dummer { namespace audio {",
        "",
    ]
    descriptors: List[str] = []

    for enum_name, aliases in CANONICAL:
        array_name = f"kData_{enum_name.lower()}"

        chosen_path: Optional[Path] = None
        for alias in aliases:
            candidate = samples_dir / alias
            if candidate.is_file():
                chosen_path = candidate
                break

        samples: Optional[List[int]] = None
        status = "missing"
        if chosen_path is not None:
            samples = read_wav(chosen_path)
            status = "ok" if samples is not None else "bad"

        if samples is None:
            # Silent stub so firmware builds before WAVs are supplied.
            samples = [0]
            tried = "/".join(aliases)
            print(f"  - SAMPLE_{enum_name}: stub (1 silent sample) [{status}, tried {tried}]")
        else:
            print(f"  + SAMPLE_{enum_name}: {chosen_path.name} -> {len(samples)} samples")

        body.append(render_array(array_name, samples))
        body.append("")
        descriptors.append(f"    {{ {array_name}, {len(samples)} }},   // SAMPLE_{enum_name}")

    body.append("const SampleDescriptor kSampleTable[SAMPLE_COUNT] = {")
    body.extend(descriptors)
    body.append("};")
    body.append("")
    body.append("}} // namespace dummer::audio")
    body.append("")
    write_if_changed(out, "\n".join(body))


def main() -> int:
    repo_root   = Path(__file__).resolve().parent.parent
    samples_dir = repo_root / "assets" / "samples"
    out_dir     = repo_root / "generated"

    print(f"wav_to_cpp: scanning {samples_dir}")
    samples_dir.mkdir(parents=True, exist_ok=True)
    out_dir.mkdir(parents=True, exist_ok=True)

    emit_header(out_dir / "samples.hpp")
    emit_source(out_dir / "samples.cpp", samples_dir)

    print(f"wav_to_cpp: wrote {out_dir / 'samples.hpp'} + {out_dir / 'samples.cpp'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
